import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Menu from "../../components/menu.js";
import Category from "../../components/category.js";
import Videoplace from "../../components/videoplace.js";

export default function Home() {
  return (
    <>
      <Head>
        <title>NeL VideoHost</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Image
            src="/logo.png"
            alt="Vercel Logo"
            className={styles.vercelLogo}
            width={63}
            height={24}
            priority
          />
          <div className={styles.descriptionSearch}>
            <input type="search" className={styles.search__input} />
            <a className={styles.search__button}>
              <Image src="/searchButton.png" width={19.78} height={19.78} />
            </a>
          </div>
          <a>
            <div className={styles.descriptionReg}>
              <Image src="/account.png" width={17} height={17} />
              <input
                type="submit"
                value="Войти"
                className={styles.reg__button}
              />
            </div>
          </a>
        </div>
        {}
      </main>
      <section className={styles.blocks__designer}>
        <div>
          <Menu />
        </div>
        <div>
          <Category />
          <Videoplace />
          
        </div>
      </section>
    </>
  );
}
